const index=[
 ['The Intellectual Woman','/journal/the-intellectual-woman','Curiosity, discernment, intelligence, archetype'],['Pretty, But All True','/journal/pretty-but-all-true','Manifesto, evidence, commerce, trust'],['How Worlds Work','/journal/how-worlds-work','Worlds, archetypes, discovery'],['Personalized World Prescription','/personalize/world-prescription','style, personalize, $49'],['Mini Edit','/personalize/mini-edit','fashion edit, $29'],['Marginalia Society No. 001','/digital/marginalia-society-001','A Room of One’s Own, reading, waitlist'],['Curiosity Archive / Intellectual Ledger','/digital/curiosity-archive','journal, notebook, commonplace book']
];
function route(){let p=location.hash.replace(/^#/,'')||'/';if(p==='/search'){openSearch();return}main.innerHTML=pages[p]||simplePage('Not found','That page does not exist.');document.title=(p==='/'?'The Journal':((main.querySelector('h1')||{}).textContent||'The Journal')+' — The Journal');window.scrollTo(0,0);bind();}
function bind(){document.querySelectorAll('.submission-form').forEach(f=>f.addEventListener('submit',submitForm));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.shop-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active')});}
async function submitForm(ev){ev.preventDefault();const f=ev.currentTarget,s=f.querySelector('.form-status'),fd=new FormData(f);s.textContent='Sending…';const payload={};for(const [k,v] of fd.entries()){if(!['email','name','website','consentEmail'].includes(k))payload[k]=v}if(f.dataset.product)payload.product=f.dataset.product;try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({submissionType:f.dataset.type,email:fd.get('email'),name:fd.get('name')||null,website:fd.get('website')||'',consentEmail:fd.get('consentEmail')==='on',sourceUrl:location.href,payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');s.textContent='Received. Your request is in the queue.';f.reset()}catch(e){s.textContent='I could not save that request. Please try again.'}}
const overlay=document.getElementById('searchOverlay'),search=document.getElementById('siteSearch'),results=document.getElementById('searchResults');function openSearch(){overlay.classList.add('open');setTimeout(()=>search.focus(),20)}function closeSearch(){overlay.classList.remove('open');if(location.hash==='#/search')history.back()}document.querySelector('[data-open-search]').onclick=e=>{e.preventDefault();openSearch()};document.querySelector('.close').onclick=closeSearch;overlay.onclick=e=>{if(e.target===overlay)closeSearch()};addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch()});search.oninput=()=>{const q=search.value.toLowerCase().trim();results.innerHTML=q?index.filter(x=>(x[0]+' '+x[2]).toLowerCase().includes(q)).map(x=>`<a href="#${x[1]}" onclick="closeSearch()"><strong>${x[0]}</strong><br><span class="notice">${x[2]}</span></a>`).join(''):'<span class="notice">Type to search.</span>'};
document.querySelector('.menu-btn').onclick=e=>{const n=document.querySelector('.nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))};
addEventListener('hashchange',route);route();
