
const SITE_NAME='THE JOURNAL';
const API='https://br-shy-snow-ay9puvn1-publicsite.compute.c-5.us-east-2.aws.neon.tech/submit';
const pages={};
function shell(title,deck,body){return `<div class="shell"><section class="page-hero"><div class="label">${SITE_NAME}</div><h1>${title}</h1><p>${deck}</p></section>${body}</div>`}
function storyCard(slug,kicker,title,deck){return `<a class="story" href="#/journal/${slug}"><div><div class="label">${kicker}</div><h3>${title}</h3></div><div><p>${deck}</p><span class="micro">Read story →</span></div></a>`}
function editionCard(slug,status,title,price,deck,cls=''){return `<a class="edition ${cls}" href="#/digital/${slug}" style="text-decoration:none"><div><span class="status">${status}</span><h3>${title}</h3><p>${deck}</p></div><div>${price?`<div class="price">${price}</div>`:''}<div class="micro">Explore →</div></div></a>`}

pages['/']=`<div class="shell">
<section class="hero">
 <div class="hero-main"><div class="kicker">Issue 001 · September 2026</div><h1>Beauty gets better when it can survive a question.</h1><p class="hero-deck">A fashion and culture publication built for women who want desire, evidence, style, context, and real life in the same room.</p><div class="hero-actions"><a class="btn light" href="#/journal">Read the Journal</a><a class="btn ghost" href="#/digital">Explore Digital Editions</a></div></div>
 <div class="hero-side"><a class="cover-card" href="#/journal/the-intellectual-woman" style="text-decoration:none"><div class="micro">Cover story</div><div class="big">THE<br>INTELLECTUAL<br>WOMAN</div><p>She does not decorate herself with intelligence. She builds a life through it.</p></a><a class="cover-card alt" href="#/digital/world-prescription" style="text-decoration:none"><div class="micro">Available now · $49</div><div class="big">MAKE<br>THIS<br>ME</div><p>You do not need to know your aesthetic. Start with what you want clothes to do for you.</p></a></div>
</section>
<section class="section rule"><div class="section-head"><div><div class="label">Latest Journal</div><h2>Read before you buy. Think while you look.</h2></div><p class="section-intro">Original editorial lives beside commerce without becoming an ad. The point is not to make everything serious. The point is to keep beauty from requiring us to stop thinking.</p></div><div class="story-grid">${storyCard('the-intellectual-woman','Archetype','The Intellectual Woman','Intelligence is not a costume, and curiosity is not a branding exercise.')}${storyCard('pretty-but-all-true','Manifesto','Pretty, But All True','Why evidence, materials, fit, sourcing, rights, usefulness, and pleasure belong on the same page.')}${storyCard('how-worlds-work','How it works','How Worlds Work','Worlds are discovery and interpretation layers — not labels you have to memorize.')}</div></section>
<section class="section rule"><div class="section-head"><div><div class="label">Digital Editions + Services</div><h2>Buy the thinking before the object.</h2></div><p class="section-intro">Zero-inventory products first: personal direction, narrow edits, and reading experiences. Anything not fully ready stays visibly on waitlist.</p></div><div class="editions">${editionCard('world-prescription','Available','Personalized World Prescription','$49','A one-page style direction built from your real life, not an aesthetic quiz.')}${editionCard('mini-edit','Available','Mini Edit','from $29','A narrow, practical 3–5 item edit with proof notes where available.')}${editionCard('marginalia-society-001','Waitlist','The Marginalia Society No. 001','','A Room of One’s Own as an evidence-aware reading experience, not a generic printable.','green')}${editionCard('curiosity-archive','Coming Soon','Curiosity Archive / Intellectual Ledger','','Part field notebook, commonplace book, evidence file, and evolving archive of a mind.','pink')}</div></section>
<section class="section rule"><div class="section-head"><div><div class="label">Worlds</div><h2>Ways into the site, not boxes to live inside.</h2></div><p class="section-intro">A World can connect clothes, books, beauty, objects, history, places, rituals, and stories. You can use one, several, or none.</p></div><div class="worlds-strip">${['Intellectual Woman','Glamoratti','Modern Prep','Soft Luxury','Heartland Daughter','Romantic Heroine'].map((w,i)=>`<a class="world-pill" href="#/worlds"><span class="micro">World ${String(i+1).padStart(2,'0')}</span><strong>${w}</strong><span>Explore →</span></a>`).join('')}</div></section>
</div>
<section class="manifesto"><div class="manifesto-inner"><div class="label">The standard</div><blockquote>Pretty, but all true.</blockquote><p>We do not need to choose between pleasure and proof. A product can be beautiful and still have to explain its materials, fit, sourcing, availability, rights, usefulness, and limits.</p><a class="btn pink" href="#/journal/pretty-but-all-true">Read the manifesto</a></div></section>
<div class="shell"><section class="section" id="newsletter"><div class="newsletter"><div><div class="label">Newsletter</div><h2>The good stuff, without the junk drawer.</h2><p>Editorial, new digital editions, Worlds, and carefully chosen shopping intelligence.</p></div><form class="submission-form" data-type="NEWSLETTER"><div class="form-inline"><div class="field"><label>Email</label><input name="email" type="email" required autocomplete="email"></div><button class="btn" type="submit">Join</button></div><input class="honeypot" name="website" tabindex="-1" autocomplete="off"><label class="checkset"><input type="checkbox" name="consentEmail" checked><span class="notice">Yes, email me Journal updates. You can unsubscribe later.</span></label><div class="form-status" aria-live="polite"></div></form></div></section></div>`;

pages['/journal']=shell('Journal','Fashion, culture, ideas, identity, objects, and the evidence behind what we choose.',`<section class="section"><div class="story-grid">${storyCard('the-intellectual-woman','Archetype','The Intellectual Woman','Thinking is part of identity — but not as performance.')}${storyCard('pretty-but-all-true','Manifesto','Pretty, But All True','The case for keeping pleasure and evidence together.')}${storyCard('how-worlds-work','System','How Worlds Work','A simpler explanation of the architecture behind discovery.')}</div></section>`);

